/**
 * Sound Service - SE & BGM management
 *
 * Uses expo-av for audio playback.
 * Cyberpunk-themed electronic sounds generated by scripts/generate-sounds.js
 *
 * BGM: 1 track at a time, crossfade on scene change
 * SE: Multiple simultaneous playback
 */

import { Audio, AVPlaybackStatusSuccess } from 'expo-av';

// ── Asset Map (static requires for Metro bundler) ───────────

const SE_ASSETS: Record<string, any> = {
  se_tap: require('../../assets/sounds/se_tap.wav'),
  se_draw_start: require('../../assets/sounds/se_draw_start.wav'),
  se_draw_complete: require('../../assets/sounds/se_draw_complete.wav'),
  se_stat_reveal: require('../../assets/sounds/se_stat_reveal.wav'),
  se_rarity_c: require('../../assets/sounds/se_rarity_c.wav'),
  se_rarity_r: require('../../assets/sounds/se_rarity_r.wav'),
  se_rarity_sr: require('../../assets/sounds/se_rarity_sr.wav'),
  se_rarity_ssr: require('../../assets/sounds/se_rarity_ssr.wav'),
  se_naming_input: require('../../assets/sounds/se_naming_input.wav'),
  se_matching: require('../../assets/sounds/se_matching.wav'),
  se_match_found: require('../../assets/sounds/se_match_found.wav'),
  se_summon_circle: require('../../assets/sounds/se_summon_circle.wav'),
  se_summon_rise: require('../../assets/sounds/se_summon_rise.wav'),
  se_vs: require('../../assets/sounds/se_vs.wav'),
  se_battle_start: require('../../assets/sounds/se_battle_start.wav'),
  se_attack: require('../../assets/sounds/se_attack.wav'),
  se_critical: require('../../assets/sounds/se_critical.wav'),
  se_special_cutin: require('../../assets/sounds/se_special_cutin.wav'),
  se_special_hit: require('../../assets/sounds/se_special_hit.wav'),
  se_status_poison: require('../../assets/sounds/se_status_poison.wav'),
  se_status_sleep: require('../../assets/sounds/se_status_sleep.wav'),
  se_status_paralyze: require('../../assets/sounds/se_status_paralyze.wav'),
  se_status_burn: require('../../assets/sounds/se_status_burn.wav'),
  se_status_freeze: require('../../assets/sounds/se_status_freeze.wav'),
  se_status_tick: require('../../assets/sounds/se_status_tick.wav'),
  se_victory: require('../../assets/sounds/se_victory.wav'),
  se_defeat: require('../../assets/sounds/se_defeat.wav'),
  se_levelup: require('../../assets/sounds/se_levelup.wav'),
  se_evolve: require('../../assets/sounds/se_evolve.wav'),
  se_equip: require('../../assets/sounds/se_equip.wav'),
  se_title_unlock: require('../../assets/sounds/se_title_unlock.wav'),
};

const BGM_ASSETS: Record<string, any> = {
  bgm_title: require('../../assets/sounds/bgm_title.wav'),
  bgm_draw: require('../../assets/sounds/bgm_draw.wav'),
  bgm_menu: require('../../assets/sounds/bgm_menu.wav'),
  bgm_battle: require('../../assets/sounds/bgm_battle.wav'),
  bgm_battle_boss: require('../../assets/sounds/bgm_battle_boss.wav'),
  bgm_result_win: require('../../assets/sounds/bgm_result_win.wav'),
  bgm_result_lose: require('../../assets/sounds/bgm_result_lose.wav'),
};

// ── State ───────────────────────────────────────────────────

let seVolume = 0.8;
let bgmVolume = 0.5;
let isMuted = false;

let currentBgm: Audio.Sound | null = null;
let currentBgmId: string | null = null;

/**
 * Initialize audio system. Call once at app startup.
 */
export async function initSound(): Promise<void> {
  try {
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: false,
      playsInSilentModeIOS: true,
      staysActiveInBackground: false,
      shouldDuckAndroid: true,
    });
  } catch (error) {
    console.warn('[SoundService] Init failed:', error);
  }
}

/**
 * Play a sound effect (short, non-blocking).
 * Multiple SE can play simultaneously.
 */
export async function playSE(seId: string): Promise<void> {
  if (isMuted) return;

  const asset = SE_ASSETS[seId];
  if (!asset) {
    console.warn(`[SoundService] Unknown SE: ${seId}`);
    return;
  }

  try {
    const { sound } = await Audio.Sound.createAsync(asset, { volume: seVolume });
    await sound.playAsync();
    sound.setOnPlaybackStatusUpdate((status) => {
      const s = status as AVPlaybackStatusSuccess;
      if (s.isLoaded && s.didJustFinish) {
        sound.unloadAsync();
      }
    });
  } catch (error) {
    console.warn(`[SoundService] SE play failed (${seId}):`, error);
  }
}

/**
 * Play BGM with crossfade. Only 1 BGM track at a time.
 */
export async function playBGM(bgmId: string): Promise<void> {
  if (currentBgmId === bgmId) return;

  const asset = BGM_ASSETS[bgmId];
  if (!asset) {
    console.warn(`[SoundService] Unknown BGM: ${bgmId}`);
    return;
  }

  if (isMuted) {
    currentBgmId = bgmId;
    return;
  }

  try {
    if (currentBgm) {
      await fadeOut(currentBgm);
      await currentBgm.unloadAsync();
      currentBgm = null;
    }

    currentBgmId = bgmId;

    const { sound } = await Audio.Sound.createAsync(asset, {
      volume: 0,
      isLooping: true,
    });
    currentBgm = sound;
    await sound.playAsync();
    await fadeIn(sound);
  } catch (error) {
    console.warn(`[SoundService] BGM play failed (${bgmId}):`, error);
  }
}

/**
 * Stop current BGM with fade out.
 */
export async function stopBGM(): Promise<void> {
  if (currentBgm) {
    await fadeOut(currentBgm);
    await currentBgm.unloadAsync();
    currentBgm = null;
    currentBgmId = null;
  }
}

// ── Fade helpers ────────────────────────────────────────────

async function fadeIn(sound: Audio.Sound, duration = 500): Promise<void> {
  const steps = 10;
  const stepDuration = duration / steps;
  for (let i = 1; i <= steps; i++) {
    await sound.setVolumeAsync((i / steps) * bgmVolume);
    await new Promise(r => setTimeout(r, stepDuration));
  }
}

async function fadeOut(sound: Audio.Sound, duration = 300): Promise<void> {
  const steps = 6;
  const stepDuration = duration / steps;
  for (let i = steps - 1; i >= 0; i--) {
    try {
      await sound.setVolumeAsync((i / steps) * bgmVolume);
      await new Promise(r => setTimeout(r, stepDuration));
    } catch {
      break;
    }
  }
}

// ── Volume control ──────────────────────────────────────────

export function setSEVolume(volume: number): void {
  seVolume = Math.max(0, Math.min(1, volume));
}

export function setBGMVolume(volume: number): void {
  bgmVolume = Math.max(0, Math.min(1, volume));
  if (currentBgm) {
    currentBgm.setVolumeAsync(bgmVolume).catch(() => {});
  }
}

export function setMuted(muted: boolean): void {
  isMuted = muted;
  if (muted && currentBgm) {
    currentBgm.setVolumeAsync(0).catch(() => {});
  } else if (!muted && currentBgm) {
    currentBgm.setVolumeAsync(bgmVolume).catch(() => {});
  }
}

export function getMuted(): boolean {
  return isMuted;
}

export function getSEVolume(): number {
  return seVolume;
}

export function getBGMVolume(): number {
  return bgmVolume;
}

/**
 * Cleanup all audio resources.
 */
export async function cleanupSound(): Promise<void> {
  if (currentBgm) {
    await currentBgm.unloadAsync().catch(() => {});
    currentBgm = null;
    currentBgmId = null;
  }
}

// ── SE IDs ──────────────────────────────────────────────────

export const SE = {
  TAP: 'se_tap',
  DRAW_START: 'se_draw_start',
  DRAW_COMPLETE: 'se_draw_complete',
  STAT_REVEAL: 'se_stat_reveal',
  RARITY_C: 'se_rarity_c',
  RARITY_R: 'se_rarity_r',
  RARITY_SR: 'se_rarity_sr',
  RARITY_SSR: 'se_rarity_ssr',
  NAMING_INPUT: 'se_naming_input',
  MATCHING: 'se_matching',
  MATCH_FOUND: 'se_match_found',
  SUMMON_CIRCLE: 'se_summon_circle',
  SUMMON_RISE: 'se_summon_rise',
  VS: 'se_vs',
  BATTLE_START: 'se_battle_start',
  ATTACK: 'se_attack',
  CRITICAL: 'se_critical',
  SPECIAL_CUTIN: 'se_special_cutin',
  SPECIAL_HIT: 'se_special_hit',
  STATUS_POISON: 'se_status_poison',
  STATUS_SLEEP: 'se_status_sleep',
  STATUS_PARALYZE: 'se_status_paralyze',
  STATUS_BURN: 'se_status_burn',
  STATUS_FREEZE: 'se_status_freeze',
  STATUS_TICK: 'se_status_tick',
  VICTORY: 'se_victory',
  DEFEAT: 'se_defeat',
  LEVELUP: 'se_levelup',
  EVOLVE: 'se_evolve',
  EQUIP: 'se_equip',
  TITLE_UNLOCK: 'se_title_unlock',
} as const;

// ── BGM IDs ─────────────────────────────────────────────────

export const BGM = {
  TITLE: 'bgm_title',
  DRAW: 'bgm_draw',
  MENU: 'bgm_menu',
  BATTLE: 'bgm_battle',
  BATTLE_BOSS: 'bgm_battle_boss',
  RESULT_WIN: 'bgm_result_win',
  RESULT_LOSE: 'bgm_result_lose',
} as const;
